# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f28536a8d80b2d525b8db679f25390bc33bb7169daa2f9b2f9a5e3c49c65c684404ccea933edb0f42b1a13e4a9fe25a0e6326433194984b0022dd1c87ef340d

test:
  secret_key_base: fd630abe6001e9fb8ab730784a52738141560eca18bff599317bfcce2ad8e6e2314dc168d78014430b91cb4283889538598863009f5d8f41cb17772bd0ee63ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
